### ISSUE TITLE
Campos con @Autowired aparecen en el RequestBody

### ISSUE THREAD

**Issue by MartinGonz** [damianwajser/spring-rest-commons-options#1]
Cuando uso el método OPTIONS,  y me devuelve el Json con los metodos disponibles y los requestBody/responseBody, encuentro que esta tomando como parte del requestBody a los campos de la entidad que tienen la annotation @Autowired, por ejemplo: 
{
    "baseUrl": "/url",
    "enpoints": [
        {
            "endpoint": "POST - /url",
            "httpMethod": "POST",
            "relativeUrl": "/url",
            "queryString": {
                "params": []
            },
            "pathVariable": {
                "params": []
            },
            "bodyRequest": [
                {
                    "name": "service",
                    "type": "service",
                    "auditable": false,
                    "validation": []
                },
                {
                    "name": "id",
                    "type": "String",
                    "auditable": false,
                    "validation": []
                }
         ]
      }
    ]
}

El campo "service" tiene la annotation @Autowired

**Comment by damianwajser** [comment]
Modificado en la v0.0.13
