### ISSUE TITLE
Armado de arbol de urls

### ISSUE THREAD

**Issue by MartinGonz** [damianwajser/spring-rest-commons-options#3]
El arbol de url esta fallando al armar las url base y las url de cada endpoint, por ejemplo el endpoint     "/private/v1/ypf?search={search}&sort={sort}&page={page}&q={q}"  genera el endpoint " /v1?search={search}&sort={sort}&page={page}&q={q}", ademas el baseUrl tendria que ser "/private/v1/ypf" pero esta generando "/v1" solamente

**Comment by damianwajser** [comment]
podes ponerme TODOS los reuqestMapping y Rest controllers que hay en este controller...
Solo las annotations con sus valores

**Comment by MartinGonz** [comment]
En el de ypf estan : 
@PostMapping("/public/v1/ypf")
@PostMapping("/private/v1/ypf")
@RequestMapping(method = RequestMethod.GET, path = "private/v1/account/{accountId}/ypf")
@RequestMapping(method = RequestMethod.GET, path = "private/v1/ypf")

Y el de mpos que tmbien lo esta  generando mal esta solamente: 
@PostMapping("/private/v1/sell/mpos")

**Comment by damianwajser** [comment]
resuelto en V.0.0.20-SNATPSHOT
