### ISSUE TITLE
El campo se documenta como "isActive" y en el response "active"

### ISSUE THREAD

**Issue by ghost** [damianwajser/spring-rest-commons-options#6]
El campo se documenta como "isActive" al igual que en la clase GenericParameter pero en el body response figura como  "active"

OPTION: /input_mode
        {
            "endpoint": "GET - /input_mode/{id}",
            "httpMethod": "GET",
            "relativeUrl": "/{id}",
            "queryString": {
                "params": []
            },
            "pathVariable": {
                "params": [
                    {
                        "required": true,
                        "name": "id",
                        "type": "Integer"
                    }
                ]
            },
            "bodyRequest": {
                "fields": [],
                "jsonSchema": null
            },
            "bodyResponse": {
                "fields": [
                        ...........................
                    {
                        "name": "isActive",
                        "type": "boolean",
                        "auditable": false
                    }
                ],

RESPONSE BODY:
{
    "id": 1,
    "code": "estoesuncode",
    "createDate": "21-11-17 12:32:14",
    "modifyDate": "21-11-17 01:04:11",
    "createUser": "aca contexto",
    "modifyUser": "aca contexto",
    "description": "666",
    "channelCode": "666",
    "inputMode": "666",
    "active": false
}

**Comment by damianwajser** [comment]
Resuelto en 0.0.19
