### ISSUE TITLE
IntrospectionException for Pageable requests

### ISSUE THREAD

**Issue by digarcia** [damianwajser/spring-rest-commons-options#8]
In:
spring-rest-commons-options
0.1.1

Using Pageable in a request:
@requestmapping(method = RequestMethod.GET ,value = "")
public Page findAllByPage(Pageable pageable) {
return repository.findAll(pageable);
}

Shows (in the documentation) the paging information in bodyRequest and pathVariable, and it should be shown only in queryString

**Comment by digarcia** [comment]
Fixed in version 0.1.3

**Comment by damianwajser** [comment]
resolved in V0.1.3
